# Generated by Django 4.2.18 on 2025-09-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=200)),
                ('name_of_society', models.CharField(max_length=255)),
                ('developer_with_address', models.TextField()),
                ('architect_with_address', models.TextField()),
                ('date_of_acceptance', models.DateField()),
                ('common_consent', models.CharField(max_length=255)),
                ('village_cts_no', models.TextField()),
                ('ownership_of_land', models.CharField(max_length=100)),
                ('area_of_plot', models.CharField(max_length=100)),
                ('buildable_reservation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buildable_reservation_area', models.CharField(blank=True, max_length=100, null=True)),
                ('non_buildable_reservation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('non_buildable_reservation_area', models.CharField(blank=True, max_length=100, null=True)),
                ('slum_declared_or_censused', models.CharField(blank=True, max_length=255, null=True)),
                ('competent_authority_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
