# Generated by Django 4.2.18 on 2025-10-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factsheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('rehab', 'Rehab'), ('layout', 'Layout'), ('sale', 'Sale')], max_length=20)),
                ('building_no', models.CharField(max_length=100)),
                ('ioa_date', models.DateField(blank=True, null=True)),
                ('no_of_floors', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_tenants', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_plinth_cc', models.DateField(blank=True, null=True)),
                ('date_of_further_cc', models.DateField(blank=True, null=True)),
                ('date_of_full_cc', models.DateField(blank=True, null=True)),
                ('date_of_lottery', models.DateField(blank=True, null=True)),
                ('date_of_part_oc', models.DateField(blank=True, null=True)),
                ('date_of_full_oc', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('rehab', 'Rehab'), ('sale', 'Sale')], max_length=20)),
                ('building_no', models.CharField(max_length=100)),
                ('date_of_visit', models.DateField(blank=True, null=True)),
                ('no_of_floors_sanctioned', models.IntegerField(blank=True, null=True)),
                ('no_of_floors_completed', models.IntegerField(blank=True, null=True)),
                ('no_of_tenants_sanctioned', models.IntegerField(blank=True, null=True)),
                ('no_of_tenants_completed', models.IntegerField(blank=True, null=True)),
                ('reasons_for_delay', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_no', models.CharField(max_length=100)),
                ('date_of_order', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransitCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_no', models.CharField(max_length=100)),
                ('floors', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_tenants', models.IntegerField(blank=True, null=True)),
                ('date_of_approval', models.DateField(blank=True, null=True)),
                ('status_on_visit', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='factsheet',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='factsheet',
            name='competent_authority_name',
        ),
        migrations.AddField(
            model_name='factsheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AnnexureIII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date_annexure3', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_bank_guarantee', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_bank_guarantee', models.CharField(blank=True, max_length=255, null=True)),
                ('land_premium_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('revised_loi_details', models.CharField(blank=True, max_length=255, null=True)),
                ('loi_issue_details', models.CharField(blank=True, max_length=255, null=True)),
                ('fsi_sanctioned', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rehab_built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pap_generated', models.IntegerField(blank=True, null=True)),
                ('permissible_sale_builtup_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tdr_generated', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tdr_granted_date', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factsheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factsheet.factsheet')),
            ],
        ),
        migrations.CreateModel(
            name='AnnexureII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competent_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_date_annexure2', models.DateField(blank=True, null=True)),
                ('tenants_total', models.IntegerField(blank=True, null=True)),
                ('tenants_eligible', models.IntegerField(blank=True, null=True)),
                ('tenants_residential', models.IntegerField(blank=True, null=True)),
                ('tenants_commercial', models.IntegerField(blank=True, null=True)),
                ('tenants_res_comm', models.IntegerField(blank=True, null=True)),
                ('tenants_others', models.IntegerField(blank=True, null=True)),
                ('tenants_pap', models.IntegerField(blank=True, null=True)),
                ('tenants_non_eligible', models.IntegerField(blank=True, null=True)),
                ('percent_eligible_consent', models.CharField(blank=True, max_length=255, null=True)),
                ('factsheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factsheet.factsheet')),
            ],
        ),
    ]
